import SvgFavorite from "./svg/Favorite";

export const iconName = {
  Facebook: 'Facebook',
  Google: 'google',
  Logo: 'Logo',
  MonogramLogo: 'monogram logo',
  Kmember: 'kmember',
  Reward: 'reward',
  Delivery: 'delivery',
  Watch: 'watch',
  Basket: 'basket',
  Vegan: 'vegan',
  Vegetarian: 'vegetarian',
  Lactose: 'lactose',
  Sugar: 'sugar',
  Gluten: 'gluten',
  Fats: 'fats',
  Oils: 'oils',
  Cruelty: 'cruelty',
  Salt: 'salt',
  France: 'france',
  Favorite: 'favorite',
  Instagram: 'instagram',
  Fb: 'fb',
  Vimeo: 'vimeo',
  Spotify: 'spotify',
  Twitter: 'twitter',
  Youtube: 'youtube',
  Mastercard: 'mastercard',
  Maestro: 'maestro',
  Visa: 'visa',
  Paypal: 'paypal',
  Bancontact: 'bancontact',
  Organic: 'organic',
  Award: 'award',
  BCorporation: 'bcorporation',
}
